### ISSUE TITLE
你好 pop 上面那个胶囊一样的东西 如何去掉呢 

### ISSUE THREAD

**Issue by yu358769601** [shirne/shirne_dialog#1]
RT

**Comment by shirne** [comment]
有一个参数没有暴露出来，等我发个小版本

**Comment by yu358769601** [comment]
最好大部分 都有自定义的方式就更好了 因为大多数时候 使用者其实是不知道这个东西如何在这个位置出现的 里面的内容 使用者当然知道是什么样子了 就是如果传入就变成自定义  不传入就走默认那种

**Comment by shirne** [comment]
是这样的。
前一段时间主要优化的OverlayEntry系列的样式，
后续对弹出框之类的还会有改进。

**Comment by yu358769601** [comment]
谢谢

**Comment by shirne** [comment]
863c396d0832ebe84b6b357c2a356340fdb467dc

已发布v4.4.1  获取不到的话晚一点再试

**Comment by yu358769601** [comment]
谢谢 谢谢
