### ISSUE TITLE
正常在中间的对话框也没有办法自定义内容的说

### ISSUE THREAD

**Issue by yu358769601** [shirne/shirne_dialog#2]
如果用本身的showdialog 呢 需要临时保存一个父节点上下文 操作比较麻烦

**Comment by shirne** [comment]
没办法自定义内容是什么意思？

**Comment by yu358769601** [comment]
就是 在中间的对话框 里面的布局内容 包括按钮的自定义布局

**Comment by shirne** [comment]
alert和confirm都是使用AlertDialog实现的，具体代码在
https://github.com/shirne/shirne_dialog/blob/master/lib/src/my_dialog.dart#L529

其中message可以为String或Widget

这部分还没有具体的优化方向，目标是增强样式的可自定义。

有具体的需求或代码，可以发出来，我会参考的
