### ISSUE TITLE
MyDialog.confirm 报错了

### ISSUE THREAD

**Issue by 107295472** [shirne/shirne_dialog#4]
Null check operator used on a null value

**Comment by 107295472** [comment]
alert也不行，是不是要更新了

**Comment by pokid** [comment]
Null check operator used on a null value 是更新的问题吗，我用最新的也是呢

**Comment by shirne** [comment]
> Null check operator used on a null value 是更新的问题吗，我用最新的也是呢

请按文档说明使用。有问题贴出代码和错误栈
